apiVersion: qos.eda.nokia.com/v1
kind: Queue
metadata:
  name: pfc-3
  namespace: clab-ai-fabric-1tier
spec:
  queueID: 3
  queueType: Pfc
  trafficType: Unicast
  
---
apiVersion: qos.eda.nokia.com/v1
kind: Queue
metadata:
  name: pfc-6
  namespace: clab-ai-fabric-1tier
spec:
  queueID: 6
  queueType: Pfc
  trafficType: Unicast

---
apiVersion: qos.eda.nokia.com/v1
kind: Queue
metadata:
  name: unicast-0
  namespace: clab-ai-fabric-1tier
spec:
  queueID: 0
  queueType: Normal
  trafficType: Unicast

---
apiVersion: qos.eda.nokia.com/v1
kind: Queue
metadata:
  name: unicast-3
  namespace: clab-ai-fabric-1tier
spec:
  queueID: 3
  queueType: Normal
  trafficType: Unicast

---
apiVersion: qos.eda.nokia.com/v1
kind: Queue
metadata:
  name: unicast-6
  namespace: clab-ai-fabric-1tier
spec:
  queueID: 6
  queueType: Normal
  trafficType: Unicast
