---
title: ai-fabric-2tier
---
graph TD
  2tier-spine-02---2tier-leaf-08
  2tier-spine-02---2tier-leaf-09
  2tier-leaf-08---2tier-gpu-svr-04
  2tier-leaf-10---2tier-gpu-svr-08
  2tier-spine-01---2tier-leaf-13
  2tier-spine-01---2tier-leaf-13
  2tier-leaf-03---2tier-gpu-svr-04
  2tier-leaf-13---2tier-gpu-svr-06
  2tier-leaf-12---2tier-gpu-svr-08
  2tier-leaf-15---2tier-gpu-svr-08
  2tier-spine-01---2tier-leaf-07
  2tier-spine-02---2tier-leaf-06
  2tier-leaf-02---2tier-gpu-svr-03
  2tier-leaf-04---2tier-gpu-svr-04
  2tier-leaf-14---2tier-gpu-svr-06
  2tier-spine-01---2tier-leaf-06
  2tier-spine-01---2tier-leaf-11
  2tier-spine-01---2tier-leaf-12
  2tier-spine-01---2tier-leaf-01
  2tier-spine-01---2tier-leaf-05
  2tier-spine-01---2tier-leaf-06
  2tier-leaf-04---2tier-gpu-svr-01
  2tier-leaf-09---2tier-gpu-svr-05
  2tier-spine-01---2tier-leaf-16
  2tier-spine-02---2tier-leaf-04
  2tier-spine-02---2tier-leaf-14
  2tier-leaf-08---2tier-gpu-svr-01
  2tier-leaf-09---2tier-gpu-svr-06
  2tier-spine-01---2tier-leaf-06
  2tier-spine-01---2tier-leaf-10
  2tier-spine-01---2tier-leaf-12
  2tier-spine-02---2tier-leaf-01
  2tier-spine-02---2tier-leaf-06
  2tier-spine-02---2tier-leaf-06
  2tier-spine-02---2tier-leaf-15
  2tier-leaf-06---2tier-gpu-svr-04
  2tier-spine-01---2tier-leaf-03
  2tier-spine-01---2tier-leaf-11
  2tier-spine-01---2tier-leaf-14
  2tier-leaf-02---2tier-gpu-svr-01
  2tier-leaf-08---2tier-gpu-svr-02
  2tier-spine-02---2tier-leaf-10
  2tier-leaf-06---2tier-gpu-svr-03
  2tier-leaf-14---2tier-gpu-svr-05
  2tier-leaf-10---2tier-gpu-svr-07
  2tier-spine-01---2tier-leaf-01
  2tier-spine-01---2tier-leaf-03
  2tier-spine-01---2tier-leaf-07
  2tier-spine-01---2tier-leaf-11
  2tier-spine-02---2tier-leaf-04
  2tier-spine-02---2tier-leaf-08
  2tier-spine-02---2tier-leaf-13
  2tier-leaf-03---2tier-gpu-svr-02
  2tier-spine-01---2tier-leaf-04
  2tier-spine-01---2tier-leaf-05
  2tier-spine-01---2tier-leaf-14
  2tier-spine-02---2tier-leaf-12
  2tier-leaf-11---2tier-gpu-svr-08
  2tier-leaf-13---2tier-gpu-svr-08
  2tier-spine-01---2tier-leaf-04
  2tier-spine-02---2tier-leaf-05
  2tier-leaf-15---2tier-gpu-svr-06
  2tier-spine-01---2tier-leaf-12
  2tier-spine-01---2tier-leaf-14
  2tier-spine-02---2tier-leaf-04
  2tier-spine-02---2tier-leaf-11
  2tier-spine-01---2tier-leaf-08
  2tier-spine-01---2tier-leaf-16
  2tier-spine-02---2tier-leaf-02
  2tier-spine-02---2tier-leaf-06
  2tier-leaf-06---2tier-gpu-svr-01
  2tier-leaf-12---2tier-gpu-svr-06
  2tier-spine-01---2tier-leaf-02
  2tier-spine-02---2tier-leaf-07
  2tier-spine-02---2tier-leaf-16
  2tier-leaf-05---2tier-gpu-svr-01
  2tier-leaf-07---2tier-gpu-svr-02
  2tier-leaf-13---2tier-gpu-svr-07
  2tier-leaf-14---2tier-gpu-svr-08
  2tier-spine-01---2tier-leaf-03
  2tier-spine-01---2tier-leaf-04
  2tier-spine-01---2tier-leaf-09
  2tier-spine-01---2tier-leaf-09
  2tier-spine-02---2tier-leaf-07
  2tier-spine-02---2tier-leaf-08
  2tier-spine-02---2tier-leaf-11
  2tier-spine-02---2tier-leaf-13
  2tier-spine-01---2tier-leaf-06
  2tier-spine-01---2tier-leaf-07
  2tier-spine-01---2tier-leaf-08
  2tier-spine-02---2tier-leaf-07
  2tier-spine-02---2tier-leaf-15
  2tier-leaf-01---2tier-gpu-svr-04
  2tier-leaf-15---2tier-gpu-svr-05
  2tier-spine-01---2tier-leaf-01
  2tier-spine-02---2tier-leaf-10
  2tier-spine-02---2tier-leaf-10
  2tier-spine-02---2tier-leaf-13
  2tier-spine-02---2tier-leaf-15
  2tier-spine-02---2tier-leaf-16
  2tier-leaf-02---2tier-gpu-svr-02
  2tier-leaf-11---2tier-gpu-svr-06
  2tier-spine-01---2tier-leaf-02
  2tier-spine-02---2tier-leaf-05
  2tier-leaf-08---2tier-gpu-svr-03
  2tier-leaf-09---2tier-gpu-svr-07
  2tier-leaf-11---2tier-gpu-svr-07
  2tier-leaf-12---2tier-gpu-svr-07
  2tier-leaf-15---2tier-gpu-svr-07
  2tier-spine-01---2tier-leaf-10
  2tier-spine-01---2tier-leaf-11
  2tier-spine-02---2tier-leaf-05
  2tier-spine-02---2tier-leaf-10
  2tier-spine-02---2tier-leaf-16
  2tier-leaf-06---2tier-gpu-svr-02
  2tier-leaf-01---2tier-gpu-svr-03
  2tier-leaf-10---2tier-gpu-svr-05
  2tier-spine-01---2tier-leaf-16
  2tier-spine-02---2tier-leaf-03
  2tier-spine-02---2tier-leaf-11
  2tier-leaf-07---2tier-gpu-svr-03
  2tier-leaf-05---2tier-gpu-svr-04
  2tier-spine-01---2tier-leaf-15
  2tier-spine-02---2tier-leaf-03
  2tier-leaf-01---2tier-gpu-svr-02
  2tier-leaf-16---2tier-gpu-svr-06
  2tier-spine-02---2tier-leaf-09
  2tier-spine-01---2tier-leaf-01
  2tier-spine-01---2tier-leaf-05
  2tier-spine-01---2tier-leaf-05
  2tier-spine-01---2tier-leaf-16
  2tier-spine-02---2tier-leaf-08
  2tier-leaf-12---2tier-gpu-svr-05
  2tier-leaf-09---2tier-gpu-svr-08
  2tier-spine-01---2tier-leaf-07
  2tier-spine-01---2tier-leaf-15
  2tier-spine-01---2tier-leaf-15
  2tier-spine-02---2tier-leaf-03
  2tier-spine-02---2tier-leaf-05
  2tier-spine-02---2tier-leaf-14
  2tier-leaf-13---2tier-gpu-svr-05
  2tier-leaf-14---2tier-gpu-svr-07
  2tier-spine-01---2tier-leaf-02
  2tier-spine-02---2tier-leaf-12
  2tier-leaf-03---2tier-gpu-svr-01
  2tier-leaf-04---2tier-gpu-svr-03
  2tier-leaf-07---2tier-gpu-svr-04
  2tier-leaf-16---2tier-gpu-svr-08
  2tier-spine-02---2tier-leaf-12
  2tier-spine-01---2tier-leaf-08
  2tier-spine-01---2tier-leaf-10
  2tier-spine-02---2tier-leaf-07
  2tier-spine-02---2tier-leaf-09
  2tier-leaf-03---2tier-gpu-svr-03
  2tier-leaf-16---2tier-gpu-svr-05
  2tier-spine-01---2tier-leaf-13
  2tier-spine-01---2tier-leaf-14
  2tier-spine-02---2tier-leaf-02
  2tier-leaf-01---2tier-gpu-svr-01
  2tier-leaf-07---2tier-gpu-svr-01
  2tier-leaf-10---2tier-gpu-svr-06
  2tier-leaf-16---2tier-gpu-svr-07
  2tier-spine-02---2tier-leaf-12
  2tier-leaf-05---2tier-gpu-svr-02
  2tier-leaf-11---2tier-gpu-svr-05
  2tier-spine-01---2tier-leaf-08
  2tier-spine-01---2tier-leaf-10
  2tier-spine-02---2tier-leaf-02
  2tier-spine-02---2tier-leaf-04
  2tier-spine-02---2tier-leaf-11
  2tier-spine-02---2tier-leaf-14
  2tier-leaf-04---2tier-gpu-svr-02
  2tier-leaf-02---2tier-gpu-svr-04
  2tier-spine-01---2tier-leaf-09
  2tier-spine-01---2tier-leaf-09
  2tier-spine-01---2tier-leaf-12
  2tier-spine-02---2tier-leaf-01
  2tier-spine-02---2tier-leaf-13
  2tier-spine-02---2tier-leaf-15
  2tier-spine-02---2tier-leaf-16
  2tier-leaf-05---2tier-gpu-svr-03
  2tier-spine-01---2tier-leaf-04
  2tier-spine-02---2tier-leaf-01
  2tier-spine-02---2tier-leaf-01
  2tier-spine-02---2tier-leaf-02
  2tier-spine-02---2tier-leaf-03
  2tier-spine-02---2tier-leaf-09
  2tier-spine-02---2tier-leaf-14
  2tier-spine-01---2tier-leaf-02
  2tier-spine-01---2tier-leaf-03
  2tier-spine-01---2tier-leaf-13
  2tier-spine-01---2tier-leaf-15
