apiVersion: core.eda.nokia.com/v1
kind: License
metadata:
  name: eda-non-prod-license-sep
  namespace: eda-system
spec:
  enabled: true
  data: "jAC0ApVHX1DAAC4AKA2uxIT76n8VikBES3t0yvcFV0hBrvikPnwQUl+kGAcxxsw2Qje1WEF1AAADABAARWRhIGxpY2Vuc2UABAATAEVEQS1bQkNdLTAuMC4qAADAACsArjHWXSp8GycMbYYwBQ5hS9qXjhLMZtPBA98zkzcbKmZMgMP2fF8eAAEAKQAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAAAAAABQAcAIF9QmgAAAAAgC9CaAAAAACAebtoAAAAAMAAIQCoio/S8NtTNNLQk3DY4JUSsscsT1Vde3RcjGedIgAAAAIAIgBOT0tJQSBJTlRFUk5BTCBOT04gUFJPRFVDVElPTgAAAAYADAABAAQAAAAAAMAALgDAmd1WqxCdV2DyNFvmkefNromIP9PMYHCCXWFsrKHp7DtIQ2ZYYT0403IAAA8AXQFEWVBmYm00QjBBdkdaZmNhUlNyVnZsMktOZkhUZTVrbGhTdmRnOWFmL2RXREFwZ3NWdUdoQlp2dHNoeU1rSFozVWFYNWZxSUVKN1NXRm1GYUxYQlVBWVdoNXNNTVFVcW8zQ3JjQ0lkcXJ4RVBuWGRGR0d4QktqYzJBd1VHbm5SWEgvRWtYMmdabTQrM1lwS09DMTFXaTdCaDBmWlgzcURadk96bk1POE1CVmVrdlo5U3U2TlFGNkw2NW5PUlRNaGRFek1jaXJVY25ubU5qVVkwcGt2OS9JRytOTzZqZ2wrQ3g3SklQNHIzUkUvM1JXMnhiMm8rYUJjVVVHWkw0d2dFVTJvUXRUMHBrRDRqR1hLSDhKNTV0dDZPK0ZoLy9iMFBta3ROQXFjM1RKMW5JY2xYZG9oZXNyTlN6c0h0ZGcwMyt1SkwwYW1QVncxUi92bDVLMkgzSXc9PQAAAAA="
